//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Solution1.Module.BusinessObjects.Database
{

    public partial class Cases : XPLiteObject
    {
        int fCaseID;
        [Key(true)]
        public int CaseID
        {
            get { return fCaseID; }
            set { SetPropertyValue<int>(nameof(CaseID), ref fCaseID, value); }
        }
        string fCaseName;
        [Size(255)]
        public string CaseName
        {
            get { return fCaseName; }
            set { SetPropertyValue<string>(nameof(CaseName), ref fCaseName, value); }
        }
        string fCaseDescription;
        [Size(SizeAttribute.Unlimited)]
        public string CaseDescription
        {
            get { return fCaseDescription; }
            set { SetPropertyValue<string>(nameof(CaseDescription), ref fCaseDescription, value); }
        }
        char fCaseType;
        public char CaseType
        {
            get { return fCaseType; }
            set { SetPropertyValue<char>(nameof(CaseType), ref fCaseType, value); }
        }
        Users fCaseCreatorID;
        [Association(@"CasesReferencesUsers")]
        public Users CaseCreatorID
        {
            get { return fCaseCreatorID; }
            set { SetPropertyValue<Users>(nameof(CaseCreatorID), ref fCaseCreatorID, value); }
        }
        Users fCaseUserID;
        [Association(@"CasesReferencesUsers1")]
        public Users CaseUserID
        {
            get { return fCaseUserID; }
            set { SetPropertyValue<Users>(nameof(CaseUserID), ref fCaseUserID, value); }
        }
        char fCaseStatus;
        public char CaseStatus
        {
            get { return fCaseStatus; }
            set { SetPropertyValue<char>(nameof(CaseStatus), ref fCaseStatus, value); }
        }
    }

}
