//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Solution1.Module.BusinessObjects.Database
{

    public partial class Customers : XPLiteObject
    {
        int fCustomerID;
        [Key]
        public int CustomerID
        {
            get { return fCustomerID; }
            set { SetPropertyValue<int>(nameof(CustomerID), ref fCustomerID, value); }
        }
        string fCustomerName;
        [Size(30)]
        public string CustomerName
        {
            get { return fCustomerName; }
            set { SetPropertyValue<string>(nameof(CustomerName), ref fCustomerName, value); }
        }
        string fCustomerSurname;
        [Size(30)]
        public string CustomerSurname
        {
            get { return fCustomerSurname; }
            set { SetPropertyValue<string>(nameof(CustomerSurname), ref fCustomerSurname, value); }
        }
        string fCustomerAdress;
        [Size(255)]
        public string CustomerAdress
        {
            get { return fCustomerAdress; }
            set { SetPropertyValue<string>(nameof(CustomerAdress), ref fCustomerAdress, value); }
        }
        string fCustomerTelNo;
        [Size(30)]
        public string CustomerTelNo
        {
            get { return fCustomerTelNo; }
            set { SetPropertyValue<string>(nameof(CustomerTelNo), ref fCustomerTelNo, value); }
        }
        string fCustomerCompany;
        [Size(255)]
        public string CustomerCompany
        {
            get { return fCustomerCompany; }
            set { SetPropertyValue<string>(nameof(CustomerCompany), ref fCustomerCompany, value); }
        }
    }

}
