//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Solution1.Module.BusinessObjects.Database
{

    public partial class Employee : XPLiteObject
    {
        int fEmployeeID;
        [Key]
        public int EmployeeID
        {
            get { return fEmployeeID; }
            set { SetPropertyValue<int>(nameof(EmployeeID), ref fEmployeeID, value); }
        }
        string fEmployeeName;
        [Size(50)]
        public string EmployeeName
        {
            get { return fEmployeeName; }
            set { SetPropertyValue<string>(nameof(EmployeeName), ref fEmployeeName, value); }
        }
        string fEmployeeSurname;
        [Size(50)]
        public string EmployeeSurname
        {
            get { return fEmployeeSurname; }
            set { SetPropertyValue<string>(nameof(EmployeeSurname), ref fEmployeeSurname, value); }
        }
        string fEmployeeTelNo;
        [Size(50)]
        public string EmployeeTelNo
        {
            get { return fEmployeeTelNo; }
            set { SetPropertyValue<string>(nameof(EmployeeTelNo), ref fEmployeeTelNo, value); }
        }
        string fEmployeeAdress;
        [Size(255)]
        public string EmployeeAdress
        {
            get { return fEmployeeAdress; }
            set { SetPropertyValue<string>(nameof(EmployeeAdress), ref fEmployeeAdress, value); }
        }
        string fEmployeeSalary;
        [Size(10)]
        public string EmployeeSalary
        {
            get { return fEmployeeSalary; }
            set { SetPropertyValue<string>(nameof(EmployeeSalary), ref fEmployeeSalary, value); }
        }
        DateTime fEmployeeStartDate;
        public DateTime EmployeeStartDate
        {
            get { return fEmployeeStartDate; }
            set { SetPropertyValue<DateTime>(nameof(EmployeeStartDate), ref fEmployeeStartDate, value); }
        }
        char fIsActive;
        public char IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<char>(nameof(IsActive), ref fIsActive, value); }
        }
    }

}
